# Generated by Django 4.0.6 on 2022-08-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='categoría'),
        ),
    ]
