# Generated by Django 4.0.6 on 2022-08-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_category_options_post_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
