# Generated by Django 4.0.6 on 2022-08-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=30, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.PositiveIntegerField(null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='user',
            name='e_mail',
            field=models.EmailField(max_length=40, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SOCIO', 'Socio'), ('VISITANTE', 'Visitante')], default='VISITANTE', max_length=12, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=30, null=True, verbose_name='Apellido'),
        ),
    ]
