# Generated by Django 4.0.6 on 2022-08-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_dni_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.PositiveIntegerField(null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='e_mail',
            field=models.EmailField(max_length=40, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='state_province',
            field=models.CharField(max_length=20, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=30, null=True, verbose_name='Apellido'),
        ),
    ]
