# Generated by Django 4.0.6 on 2022-08-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('e_mail', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('dni', models.PositiveIntegerField()),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('celphone', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state_province', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
