# Generated by Django 4.0.6 on 2022-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicación', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
