# Generated by Django 4.0.6 on 2022-08-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacion',
            name='subtitulo',
        ),
    ]
